version: '2.1'
services:
  Router:
    build: ./Router
    privileged: true
    network_mode: "host"
    expose: 
      - "5672"
    depends_on:
      - RabbitMQ
    labels:
      io.balena.features.supervisor-api: '1'  
  Power:
    build: ./Power
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
    labels:
      io.balena.features.supervisor-api: '1'    
  RabbitMQ:
    build: ./RabbitMQ
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
