version: '2.1'
services:
  Router:
    build: ./Router
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
    labels:
      io.balena.features.supervisor-api: '1'  
  Power:
    build: ./Power
    privileged: true
    network_mode: "host"
    depends_on:
      - RabbitMQ
    labels:
      io.balena.features.supervisor-api: '1'         
  RabbitMQ:
    image: "arm32v7/rabbitmq:3.8-management"
    network_mode: "host"
    privileged: true
    expose: 
      - "5672"
      - "15672"
    labels:
      io.balena.features.supervisor-api: '1'
